// <auto-generated />
using System;
using Cleaning.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cleaning.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624102729_AlignWithUpdatedCleaningSchema")]
    partial class AlignWithUpdatedCleaningSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "account_status", new[] { "active", "banned", "pending_verification" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ai_sender_type", new[] { "user", "ai" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "availability_status", new[] { "available", "blocked", "booked" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_status", new[] { "pending_payment", "paid_pending_worker", "accepted", "reschedule_requested", "in_progress", "completed", "cancelled", "refunded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_type", new[] { "scheduled", "immediate" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cleanliness_level", new[] { "clean", "light", "medium", "heavy" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", new[] { "booking", "payment", "schedule", "system", "ai" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "cash", "mo_mo", "vn_pay", "zalo_pay", "bank_transfer" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_status", new[] { "pending", "success", "failed", "refunded", "partially_refunded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payout_status", new[] { "pending", "paid", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "photo_type", new[] { "before", "after", "issue", "ai_reference" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "property_type", new[] { "apartment", "house" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "reschedule_status", new[] { "pending", "accepted", "rejected", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "service_unit_type", new[] { "hour" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "client", "worker", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "verification_purpose", new[] { "email_verification", "phone_verification", "password_reset" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "worker_online_status", new[] { "offline", "online", "busy" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cleaning.DAL.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsPhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_phone_verified");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text")
                        .HasColumnName("password_salt");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("account_status")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("accounts_pkey");

                    b.HasIndex(new[] { "Email" }, "accounts_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "accounts_phone_number_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "idx_accounts_email");

                    b.HasIndex(new[] { "PhoneNumber" }, "idx_accounts_phone");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("chk_account_identifier", "email IS NOT NULL OR phone_number IS NOT NULL");

                            t.HasCheckConstraint("chk_password_pair", "(password_hash IS NULL AND password_salt IS NULL) OR (password_hash IS NOT NULL AND password_salt IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.AiCleanlinessAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingPhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_photo_id");

                    b.Property<int>("CleanlinessLevel")
                        .HasColumnType("cleanliness_level")
                        .HasColumnName("cleanliness_level");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DetectedIssues")
                        .HasColumnType("jsonb")
                        .HasColumnName("detected_issues");

                    b.Property<string>("SuggestedTasks")
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_tasks");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("ai_cleanliness_analyses_pkey");

                    b.HasIndex(new[] { "BookingPhotoId" }, "idx_ai_cleanliness_photo");

                    b.ToTable("ai_cleanliness_analyses", null, t =>
                        {
                            t.HasCheckConstraint("chk_ai_cleanliness_confidence", "confidence_score BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.AiConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("ai_conversations_pkey");

                    b.HasIndex(new[] { "UserId" }, "idx_ai_conversations_user");

                    b.ToTable("ai_conversations", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.AiInferenceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("ai_inference_logs_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("ai_inference_logs", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.AiMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("SenderType")
                        .HasColumnType("ai_sender_type")
                        .HasColumnName("sender_type");

                    b.HasKey("Id")
                        .HasName("ai_messages_pkey");

                    b.HasIndex(new[] { "ConversationId" }, "idx_ai_messages_conversation");

                    b.ToTable("ai_messages", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end_time");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start_time");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<int>("BookingType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("booking_type")
                        .HasDefaultValue(0)
                        .HasColumnName("booking_type");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("DurationHours")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("duration_hours");

                    b.Property<decimal>("ExtraFee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("extra_fee");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ScheduledEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end_time");

                    b.Property<DateTime>("ScheduledStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_time");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<int>("Status")
                        .HasColumnType("booking_status")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("bookings_pkey");

                    b.HasIndex("AddressId");

                    b.HasIndex("ServiceId");

                    b.HasIndex(new[] { "ClientId" }, "idx_bookings_client");

                    b.HasIndex(new[] { "ScheduledStartTime", "ScheduledEndTime" }, "idx_bookings_schedule");

                    b.HasIndex(new[] { "Status" }, "idx_bookings_status");

                    b.HasIndex(new[] { "WorkerId" }, "idx_bookings_worker");

                    b.ToTable("bookings", null, t =>
                        {
                            t.HasCheckConstraint("chk_booking_client_worker_different", "worker_id IS NULL OR client_id <> worker_id");

                            t.HasCheckConstraint("chk_booking_time", "scheduled_end_time > scheduled_start_time");
                        });
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.BookingCancellation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<decimal>("CancellationFee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cancellation_fee");

                    b.Property<Guid>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<decimal>("RefundAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("refund_amount");

                    b.HasKey("Id")
                        .HasName("booking_cancellations_pkey");

                    b.HasIndex("CancelledBy");

                    b.HasIndex(new[] { "BookingId" }, "booking_cancellations_booking_id_key")
                        .IsUnique();

                    b.ToTable("booking_cancellations", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.BookingPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("PhotoType")
                        .HasColumnType("photo_type")
                        .HasColumnName("photo_type");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("booking_photos_pkey");

                    b.HasIndex("UploadedBy");

                    b.HasIndex(new[] { "BookingId" }, "idx_booking_photos_booking");

                    b.ToTable("booking_photos", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.BookingRescheduleRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("NewEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_end_time");

                    b.Property<DateTime>("NewStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_start_time");

                    b.Property<DateTime>("OldEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("old_end_time");

                    b.Property<DateTime>("OldStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("old_start_time");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<Guid?>("RespondedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("responded_by");

                    b.Property<int>("Status")
                        .HasColumnType("reschedule_status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("booking_reschedule_requests_pkey");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("RespondedBy");

                    b.HasIndex(new[] { "BookingId", "Status" }, "idx_reschedule_booking_status");

                    b.ToTable("booking_reschedule_requests", null, t =>
                        {
                            t.HasCheckConstraint("chk_reschedule_new_time", "new_end_time > new_start_time");

                            t.HasCheckConstraint("chk_reschedule_old_time", "old_end_time > old_start_time");
                        });
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.BookingStatusLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("NewStatus")
                        .HasColumnType("booking_status")
                        .HasColumnName("new_status");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("booking_status")
                        .HasColumnName("old_status");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("booking_status_logs_pkey");

                    b.HasIndex("ChangedBy");

                    b.HasIndex(new[] { "BookingId" }, "idx_booking_logs_booking");

                    b.ToTable("booking_status_logs", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.HasKey("Id")
                        .HasName("external_logins_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex(new[] { "Provider", "ProviderKey" }, "external_logins_provider_provider_key_key")
                        .IsUnique();

                    b.ToTable("external_logins", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("knowledge_documents_pkey");

                    b.ToTable("knowledge_documents", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("notification_type")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex("BookingId");

                    b.HasIndex(new[] { "UserId" }, "idx_notifications_user_unread")
                        .HasFilter("is_read = FALSE");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Method")
                        .HasColumnType("payment_method")
                        .HasColumnName("method");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<int>("Status")
                        .HasColumnType("payment_status")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("payments_pkey");

                    b.HasIndex(new[] { "BookingId" }, "idx_payments_booking");

                    b.HasIndex(new[] { "Status" }, "idx_payments_status");

                    b.HasIndex(new[] { "BookingId" }, "payments_booking_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "TransactionId" }, "payments_transaction_id_key")
                        .IsUnique();

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("chk_payments_amount", "amount >= 0");
                        });
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("profiles_pkey");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex(new[] { "AccountId" }, "idx_refresh_tokens_account");

                    b.HasIndex(new[] { "TokenHash" }, "idx_refresh_tokens_token_hash");

                    b.HasIndex(new[] { "TokenHash" }, "refresh_tokens_token_hash_key")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("refunds_pkey");

                    b.HasIndex("PaymentId");

                    b.ToTable("refunds", null, t =>
                        {
                            t.HasCheckConstraint("chk_refunds_amount", "amount >= 0");
                        });
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewee_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.HasKey("Id")
                        .HasName("reviews_pkey");

                    b.HasIndex("ReviewerId");

                    b.HasIndex(new[] { "BookingId" }, "idx_reviews_booking");

                    b.HasIndex(new[] { "RevieweeId" }, "idx_reviews_reviewee");

                    b.HasIndex(new[] { "BookingId", "ReviewerId", "RevieweeId" }, "reviews_booking_id_reviewer_id_reviewee_id_key")
                        .IsUnique();

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("chk_review_not_self", "reviewer_id <> reviewee_id");

                            t.HasCheckConstraint("chk_reviews_rating", "rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MinimumHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("minimum_hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PropertyType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("property_type")
                        .HasDefaultValue(0)
                        .HasColumnName("property_type");

                    b.Property<int>("UnitType")
                        .HasColumnType("service_unit_type")
                        .HasColumnName("unit_type");

                    b.HasKey("Id")
                        .HasName("services_pkey");

                    b.HasIndex(new[] { "PropertyType", "IsActive" }, "idx_services_property_active");

                    b.HasIndex(new[] { "Name" }, "services_name_key")
                        .IsUnique();

                    b.ToTable("services", null, t =>
                        {
                            t.HasCheckConstraint("chk_services_base_price", "base_price >= 0");

                            t.HasCheckConstraint("chk_services_minimum_hours", "minimum_hours > 0");
                        });
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AddressText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("label")
                        .HasDefaultValueSql("'Home'::text");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<int>("PropertyType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("property_type")
                        .HasDefaultValue(0)
                        .HasColumnName("property_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_addresses_pkey");

                    b.HasIndex(new[] { "UserId" }, "idx_user_addresses_user");

                    b.ToTable("user_addresses", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<int>("Purpose")
                        .HasColumnType("verification_purpose")
                        .HasColumnName("purpose");

                    b.HasKey("Id")
                        .HasName("verification_codes_pkey");

                    b.HasIndex(new[] { "AccountId", "Purpose" }, "idx_verification_codes_account_purpose")
                        .HasFilter("is_used = FALSE");

                    b.ToTable("verification_codes", (string)null);
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.WorkerAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("availability_status")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("worker_availability_pkey");

                    b.HasIndex(new[] { "StartTime", "EndTime", "Status" }, "idx_worker_availability_time_status");

                    b.HasIndex(new[] { "WorkerId", "StartTime", "EndTime" }, "idx_worker_availability_worker_time");

                    b.ToTable("worker_availability", null, t =>
                        {
                            t.HasCheckConstraint("chk_worker_availability_time", "end_time > start_time");
                        });
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.WorkerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("average_rating")
                        .HasDefaultValueSql("5.00");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("CurrentLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("current_lat");

                    b.Property<decimal?>("CurrentLng")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("current_lng");

                    b.Property<bool>("ImmediateBookingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("immediate_booking_enabled");

                    b.Property<int>("OnlineStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("worker_online_status")
                        .HasDefaultValue(0)
                        .HasColumnName("online_status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("UserId")
                        .HasName("worker_profiles_pkey");

                    b.HasIndex(new[] { "OnlineStatus", "ImmediateBookingEnabled" }, "idx_worker_online_status");

                    b.ToTable("worker_profiles", null, t =>
                        {
                            t.HasCheckConstraint("chk_worker_rating", "average_rating BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.WorkerService", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ExperienceMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("experience_months");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.HasKey("WorkerId", "ServiceId")
                        .HasName("worker_services_pkey");

                    b.HasIndex(new[] { "ServiceId" }, "idx_worker_services_service");

                    b.ToTable("worker_services", null, t =>
                        {
                            t.HasCheckConstraint("chk_worker_services_experience", "experience_months >= 0");
                        });
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.AiCleanlinessAnalysis", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.BookingPhoto", "BookingPhoto")
                        .WithMany("AiCleanlinessAnalyses")
                        .HasForeignKey("BookingPhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ai_cleanliness_analyses_booking_photo_id_fkey");

                    b.Navigation("BookingPhoto");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.AiConversation", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Account", "User")
                        .WithMany("AiConversations")
                        .HasForeignKey("UserId")
                        .HasConstraintName("ai_conversations_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.AiInferenceLog", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Account", "User")
                        .WithMany("AiInferenceLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("ai_inference_logs_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.AiMessage", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.AiConversation", "Conversation")
                        .WithMany("AiMessages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ai_messages_conversation_id_fkey");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Booking", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.UserAddress", "Address")
                        .WithMany("Bookings")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("bookings_address_id_fkey");

                    b.HasOne("Cleaning.DAL.Entities.Profile", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_client_id_fkey");

                    b.HasOne("Cleaning.DAL.Entities.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_service_id_fkey");

                    b.HasOne("Cleaning.DAL.Entities.WorkerProfile", "Worker")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("bookings_worker_id_fkey");

                    b.Navigation("Address");

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.BookingCancellation", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Booking", "Booking")
                        .WithMany("BookingCancellations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("booking_cancellations_booking_id_fkey");

                    b.HasOne("Cleaning.DAL.Entities.Account", "CancelledByNavigation")
                        .WithMany("BookingCancellations")
                        .HasForeignKey("CancelledBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("booking_cancellations_cancelled_by_fkey");

                    b.Navigation("Booking");

                    b.Navigation("CancelledByNavigation");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.BookingPhoto", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Booking", "Booking")
                        .WithMany("BookingPhotos")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("booking_photos_booking_id_fkey");

                    b.HasOne("Cleaning.DAL.Entities.Account", "UploadedByNavigation")
                        .WithMany("BookingPhotos")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("booking_photos_uploaded_by_fkey");

                    b.Navigation("Booking");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.BookingRescheduleRequest", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Booking", "Booking")
                        .WithMany("BookingRescheduleRequests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("booking_reschedule_requests_booking_id_fkey");

                    b.HasOne("Cleaning.DAL.Entities.Account", "RequestedByNavigation")
                        .WithMany("BookingRescheduleRequestRequesters")
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("booking_reschedule_requests_requested_by_fkey");

                    b.HasOne("Cleaning.DAL.Entities.Account", "RespondedByNavigation")
                        .WithMany("BookingRescheduleRequestResponders")
                        .HasForeignKey("RespondedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("booking_reschedule_requests_responded_by_fkey");

                    b.Navigation("Booking");

                    b.Navigation("RequestedByNavigation");

                    b.Navigation("RespondedByNavigation");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.BookingStatusLog", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Booking", "Booking")
                        .WithMany("BookingStatusLogs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("booking_status_logs_booking_id_fkey");

                    b.HasOne("Cleaning.DAL.Entities.Account", "ChangedByNavigation")
                        .WithMany("BookingStatusLogs")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("booking_status_logs_changed_by_fkey");

                    b.Navigation("Booking");

                    b.Navigation("ChangedByNavigation");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.ExternalLogin", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Account", "Account")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("external_logins_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Notification", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Booking", "Booking")
                        .WithMany("Notifications")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("notifications_booking_id_fkey");

                    b.HasOne("Cleaning.DAL.Entities.Account", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Payment", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("Cleaning.DAL.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("payments_booking_id_fkey");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Profile", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Account", "IdNavigation")
                        .WithOne("Profile")
                        .HasForeignKey("Cleaning.DAL.Entities.Profile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("profiles_id_fkey");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Refund", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refunds_payment_id_fkey");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Review", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reviews_booking_id_fkey");

                    b.HasOne("Cleaning.DAL.Entities.Profile", "Reviewee")
                        .WithMany("ReviewReviewees")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reviews_reviewee_id_fkey");

                    b.HasOne("Cleaning.DAL.Entities.Profile", "Reviewer")
                        .WithMany("ReviewReviewers")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reviews_reviewer_id_fkey");

                    b.Navigation("Booking");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.UserAddress", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Profile", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_addresses_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.VerificationCode", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Account", "Account")
                        .WithMany("VerificationCodes")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("verification_codes_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.WorkerAvailability", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.WorkerProfile", "Worker")
                        .WithMany("WorkerAvailabilities")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("worker_availability_worker_id_fkey");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.WorkerProfile", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Profile", "User")
                        .WithOne("WorkerProfile")
                        .HasForeignKey("Cleaning.DAL.Entities.WorkerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("worker_profiles_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.WorkerService", b =>
                {
                    b.HasOne("Cleaning.DAL.Entities.Service", "Service")
                        .WithMany("WorkerServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("worker_services_service_id_fkey");

                    b.HasOne("Cleaning.DAL.Entities.WorkerProfile", "Worker")
                        .WithMany("WorkerServices")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("worker_services_worker_id_fkey");

                    b.Navigation("Service");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Account", b =>
                {
                    b.Navigation("AiConversations");

                    b.Navigation("AiInferenceLogs");

                    b.Navigation("BookingCancellations");

                    b.Navigation("BookingPhotos");

                    b.Navigation("BookingRescheduleRequestRequesters");

                    b.Navigation("BookingRescheduleRequestResponders");

                    b.Navigation("BookingStatusLogs");

                    b.Navigation("ExternalLogins");

                    b.Navigation("Notifications");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("VerificationCodes");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.AiConversation", b =>
                {
                    b.Navigation("AiMessages");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Booking", b =>
                {
                    b.Navigation("BookingCancellations");

                    b.Navigation("BookingPhotos");

                    b.Navigation("BookingRescheduleRequests");

                    b.Navigation("BookingStatusLogs");

                    b.Navigation("Notifications");

                    b.Navigation("Payment");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.BookingPhoto", b =>
                {
                    b.Navigation("AiCleanlinessAnalyses");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Payment", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Profile", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ReviewReviewees");

                    b.Navigation("ReviewReviewers");

                    b.Navigation("UserAddresses");

                    b.Navigation("WorkerProfile");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.Service", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("WorkerServices");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.UserAddress", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Cleaning.DAL.Entities.WorkerProfile", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("WorkerAvailabilities");

                    b.Navigation("WorkerServices");
                });
#pragma warning restore 612, 618
        }
    }
}
