name: Flutter Build CI

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'CleanAI/**' # Chỉ trigger khi code FE thay đổi

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' 

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Install Dependencies
        working-directory: ./CleanAI # Bắt buộc trỏ vào thư mục FE
        run: flutter pub get

      - name: Build APK Release
        working-directory: ./CleanAI # Bắt buộc trỏ vào thư mục FE
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          # Đường dẫn lấy file APK sau khi build xong
          path: CleanAI/build/app/outputs/flutter-apk/app-release.apk