services:
  api:
    build: .
    image: buingoctam/cleaning-api:latest
    container_name: cleaning_api
    ports:
      - "5000:8080" 
    depends_on:
      - ollama
      # Đã bỏ - db vì API giờ phụ thuộc vào DB trên máy tính (Host)
    environment:
      - AiConfig__OllamaUrl=http://ollama:11434 
      - ASPNETCORE_ENVIRONMENT=Development
      
      # 1. ĐỔI HOST THÀNH host.docker.internal ĐỂ TRỎ RA MÁY THẬT (POSTGRES 17)
      # 2. Vẫn đọc Username và Password từ file .env
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=PRM393_Cleaning;Username=${DB_USER};Password=${DB_PASSWORD}
      
      # Đọc chuỗi JWT bằng biến từ .env
      - JwtConfig__Secret=${JWT_SECRET}
      - JwtConfig__Issuer=CleaningAppBackend
      - JwtConfig__Audience=CleaningAppFlutter
      - JwtConfig__AccessTokenExpirationMinutes=15
      - JwtConfig__RefreshTokenExpirationDays=7
    networks:
      - cleaning_network

  db:
    image: postgres:16
    container_name: cleaning_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=PRM393_Cleaning
    ports:
      - "${DB_HOST_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cleaning_network

  ollama:
    image: ollama/ollama:latest
    container_name: local_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - cleaning_network

networks:
  cleaning_network:
    driver: bridge

volumes:
  ollama_data:
  postgres_data:
